<a href="https://colab.research.google.com/github/sathkumara-smna/258739K/blob/main/CapstoneLTE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [117]:
import pandas as pd

# Raw GitHub file URL
url = "https://raw.githubusercontent.com/sathkumara-smna/258739K/main/LTE_01_03_2026%20-%20Lite.xlsx"
#url = "https://raw.githubusercontent.com/sathkumara-smna/258739K/main/LTE%20Master%20Raw%20Data.xlsx"

# Load Excel file
df = pd.read_excel(url)

# Show first few rows
df.head()

,Site_ID,Cell_ID,Sector_ID,trigger_ID,datetime,traffic_load_mbps,Total Power
0,101,10111,11,1,2026-03-01 00:00,11.90,17.28
1,101,10111,11,2,2026-03-01 00:15,12.03,17.28
2,101,10111,11,3,2026-03-01 00:30,12.08,17.28
3,101,10111,11,4,2026-03-01 00:45,11.96,17.28
4,101,10111,11,5,2026-03-01 01:00,12.48,17.29

In [118]:
url1 = "https://raw.githubusercontent.com/sathkumara-smna/258739K/main/4G%20Site%20information.xlsx"

# Load into dataframe
info_4g = pd.read_excel(url1)
info_4g.head()

   #  Site_ID        Site Name  lbbp_boards  BBU 3900  BBU 3910  rru_count
0  1      101     AIRPORT_MAHE            2         1         1         12
1  2      102  AIRPORT_PRASLIN            1         1         0          4
2  3      103     ANSE_AUX_PIN            2         1         1         12
3  4      104  ANSE_CIMITIERRE            1         1         0          4
4  5      105       ANSE_FAURE            1         1         1         10

In [119]:
url2 = "https://raw.githubusercontent.com/sathkumara-smna/258739K/main/LTE%20Traffic%20Bands.xlsx"

# Load into dataframe
ltetrafficbands = pd.read_excel(url2)
ltetrafficbands.head()

   Lower  Upper  UpperValue  lbbp_power  rru_power
0      0     15          15           3         10
1     15     30          30           6         20
2     30     45          45           9         30
3     45     60          60          12         40
4     60     75          75          15         50

In [120]:
df["BBU3900"] = 0
df["BBU3910"] = 0
df["rru_count"] = 0
df["lbbp_boards"] = 0
df["BBU3900BP"] = 0
df["BBU3910BP"] = 0
df["lbbp_bp"] = 0
df["ltetrfband"] = 0
df["ltetrfbandmax"] = 0
df["ltetrfbandextrapower"] = 0
df["calctotalpower"] = 0
df["rru_base_power"] = 180
df["rru_extra_band"] = 0
df["rru_extra_power"] = 0
df.head()

,Site_ID,Cell_ID,Sector_ID,trigger_ID,datetime,traffic_load_mbps,Total Power,BBU3900,BBU3910,rru_count,...,BBU3900BP,BBU3910BP,lbbp_bp,ltetrfband,ltetrfbandmax,ltetrfbandextrapower,calctotalpower,rru_base_power,rru_extra_band,rru_extra_power
0,101,10111,11,1,2026-03-01 00:00,11.90,17.28,0,0,0,...,0,0,0,0,0,0,0,180,0,0
1,101,10111,11,2,2026-03-01 00:15,12.03,17.28,0,0,0,...,0,0,0,0,0,0,0,180,0,0
2,101,10111,11,3,2026-03-01 00:30,12.08,17.28,0,0,0,...,0,0,0,0,0,0,0,180,0,0
3,101,10111,11,4,2026-03-01 00:45,11.96,17.28,0,0,0,...,0,0,0,0,0,0,0,180,0,0
4,101,10111,11,5,2026-03-01 01:00,12.48,17.29,0,0,0,...,0,0,0,0,0,0,0,180,0,0

In [121]:
# Merge BBU columns from info_4g using Site_ID
df = df.merge(
    info_4g[["Site_ID", "BBU 3900", "BBU 3910"]],
    on="Site_ID",
    how="left"
)

# Fill df columns
df["BBU3900"] = df["BBU 3900"].fillna(0).astype(int)
df["BBU3910"] = df["BBU 3910"].fillna(0).astype(int)

# Remove temporary columns
df.drop(columns=["BBU 3900", "BBU 3910"], inplace=True)

# Preview
df[["Site_ID", "BBU3900", "BBU3910"]].head()

   Site_ID  BBU3900  BBU3910
0      101        1        1
1      101        1        1
2      101        1        1
3      101        1        1
4      101        1        1

In [122]:
df = df.merge(
    info_4g[["Site_ID", "rru_count", "lbbp_boards"]],
    on="Site_ID",
    how="left",
    suffixes=("", "_from_4g")
)

# Fill values
df["rru_count"] = df["rru_count_from_4g"].fillna(0).astype(int)
df["lbbp_boards"] = df["lbbp_boards_from_4g"].fillna(0).astype(int)

# Clean up
df.drop(columns=["rru_count_from_4g", "lbbp_boards_from_4g"], inplace=True)

df.head()

,Site_ID,Cell_ID,Sector_ID,trigger_ID,datetime,traffic_load_mbps,Total Power,BBU3900,BBU3910,rru_count,...,BBU3900BP,BBU3910BP,lbbp_bp,ltetrfband,ltetrfbandmax,ltetrfbandextrapower,calctotalpower,rru_base_power,rru_extra_band,rru_extra_power
0,101,10111,11,1,2026-03-01 00:00,11.90,17.28,1,1,12,...,0,0,0,0,0,0,0,180,0,0
1,101,10111,11,2,2026-03-01 00:15,12.03,17.28,1,1,12,...,0,0,0,0,0,0,0,180,0,0
2,101,10111,11,3,2026-03-01 00:30,12.08,17.28,1,1,12,...,0,0,0,0,0,0,0,180,0,0
3,101,10111,11,4,2026-03-01 00:45,11.96,17.28,1,1,12,...,0,0,0,0,0,0,0,180,0,0
4,101,10111,11,5,2026-03-01 01:00,12.48,17.29,1,1,12,...,0,0,0,0,0,0,0,180,0,0

In [123]:
import numpy as np

df["BBU3900BP"] = np.where(
    df["rru_count"] == 0,
    0,
    (55 * df["BBU3900"] / df["rru_count"]).round(2)
)
df["BBU3910BP"] = np.where(
    df["rru_count"] == 0,
    0,
    (65 * df["BBU3910"] / df["rru_count"]).round(2)
)
df.head()

,Site_ID,Cell_ID,Sector_ID,trigger_ID,datetime,traffic_load_mbps,Total Power,BBU3900,BBU3910,rru_count,...,BBU3900BP,BBU3910BP,lbbp_bp,ltetrfband,ltetrfbandmax,ltetrfbandextrapower,calctotalpower,rru_base_power,rru_extra_band,rru_extra_power
0,101,10111,11,1,2026-03-01 00:00,11.90,17.28,1,1,12,...,4.58,5.42,0,0,0,0,0,180,0,0
1,101,10111,11,2,2026-03-01 00:15,12.03,17.28,1,1,12,...,4.58,5.42,0,0,0,0,0,180,0,0
2,101,10111,11,3,2026-03-01 00:30,12.08,17.28,1,1,12,...,4.58,5.42,0,0,0,0,0,180,0,0
3,101,10111,11,4,2026-03-01 00:45,11.96,17.28,1,1,12,...,4.58,5.42,0,0,0,0,0,180,0,0
4,101,10111,11,5,2026-03-01 01:00,12.48,17.29,1,1,12,...,4.58,5.42,0,0,0,0,0,180,0,0

In [124]:
import numpy as np

df["lbbp_bp"] = np.where(
    df["rru_count"] == 0,
    0,
    (42.5 * df["lbbp_boards"] / df["rru_count"]).round(2)
)
df[["lbbp_boards", "rru_count", "lbbp_bp"]].head()

   lbbp_boards  rru_count  lbbp_bp
0            2         12     7.08
1            2         12     7.08
2            2         12     7.08
3            2         12     7.08
4            2         12     7.08

In [125]:
def get_lbbp_power(load):
    match = ltetrafficbands[
        (ltetrafficbands["Lower"] <= load) &
        (ltetrafficbands["Upper"] > load)
    ]

    if not match.empty:
        return match.iloc[0]["lbbp_power"]
    return 0  # default if no match

df["ltetrfband"] = df["traffic_load_mbps"].apply(get_lbbp_power)
df[["traffic_load_mbps", "ltetrfband"]].head()

   traffic_load_mbps  ltetrfband
0              11.90           3
1              12.03           3
2              12.08           3
3              11.96           3
4              12.48           3

In [126]:
df.iloc[10:12]

,Site_ID,Cell_ID,Sector_ID,trigger_ID,datetime,traffic_load_mbps,Total Power,BBU3900,BBU3910,rru_count,...,BBU3900BP,BBU3910BP,lbbp_bp,ltetrfband,ltetrfbandmax,ltetrfbandextrapower,calctotalpower,rru_base_power,rru_extra_band,rru_extra_power
10,101,10111,11,11,2026-03-01 02:30,14.05,17.31,1,1,12,...,4.58,5.42,7.08,3,0,0,0,180,0,0
11,101,10111,11,12,2026-03-01 02:45,14.04,17.31,1,1,12,...,4.58,5.42,7.08,3,0,0,0,180,0,0
12,101,10111,11,13,2026-03-01 03:00,14.01,17.31,1,1,12,...,4.58,5.42,7.08,3,0,0,0,180,0,0
13,101,10111,11,14,2026-03-01 03:15,14.86,17.33,1,1,12,...,4.58,5.42,7.08,3,0,0,0,180,0,0
14,101,10111,11,15,2026-03-01 03:30,14.73,17.33,1,1,12,...,4.58,5.42,7.08,3,0,0,0,180,0,0
15,101,10111,11,16,2026-03-01 03:45,15.32,17.34,1,1,12,...,4.58,5.42,7.08,6,0,0,0,180,0,0
16,101,10111,11,17,2026-03-01 04:00,15.63,17.34,1,1,12,...,4.58,5.42,7.08,6,0,0,0,180,0,0
17,101,10111,11,18,2026-03-01 04:15,15.95,17.35,1,1,12,...,4.58,5.42,7.08,6,0,0,0,180,0,0
18,101,10111,11,19,2026-03-01 04:30,15.80,17.34,1,1,12,...,4.58,5.42,7.08,6,0,0,0,180,0,0
19,101,10111,11,20,2026-03-01 04:45,15.81,17.34,1,1,12,...,4.58,5.42,7.08,6,0,0,0,180,0,0

In [127]:
def get_upper_band(load):
    match = ltetrafficbands[
        (ltetrafficbands["Lower"] <= load) &
        (ltetrafficbands["Upper"] > load)
    ]

    if not match.empty:
        return match.iloc[0]["UpperValue"]
    return 0

df["ltetrfbandmax"] = df["traffic_load_mbps"].apply(get_upper_band)
df.iloc[10:12]

,Site_ID,Cell_ID,Sector_ID,trigger_ID,datetime,traffic_load_mbps,Total Power,BBU3900,BBU3910,rru_count,...,BBU3900BP,BBU3910BP,lbbp_bp,ltetrfband,ltetrfbandmax,ltetrfbandextrapower,calctotalpower,rru_base_power,rru_extra_band,rru_extra_power
10,101,10111,11,11,2026-03-01 02:30,14.05,17.31,1,1,12,...,4.58,5.42,7.08,3,15,0,0,180,0,0
11,101,10111,11,12,2026-03-01 02:45,14.04,17.31,1,1,12,...,4.58,5.42,7.08,3,15,0,0,180,0,0
12,101,10111,11,13,2026-03-01 03:00,14.01,17.31,1,1,12,...,4.58,5.42,7.08,3,15,0,0,180,0,0
13,101,10111,11,14,2026-03-01 03:15,14.86,17.33,1,1,12,...,4.58,5.42,7.08,3,15,0,0,180,0,0
14,101,10111,11,15,2026-03-01 03:30,14.73,17.33,1,1,12,...,4.58,5.42,7.08,3,15,0,0,180,0,0
15,101,10111,11,16,2026-03-01 03:45,15.32,17.34,1,1,12,...,4.58,5.42,7.08,6,30,0,0,180,0,0
16,101,10111,11,17,2026-03-01 04:00,15.63,17.34,1,1,12,...,4.58,5.42,7.08,6,30,0,0,180,0,0
17,101,10111,11,18,2026-03-01 04:15,15.95,17.35,1,1,12,...,4.58,5.42,7.08,6,30,0,0,180,0,0
18,101,10111,11,19,2026-03-01 04:30,15.80,17.34,1,1,12,...,4.58,5.42,7.08,6,30,0,0,180,0,0
19,101,10111,11,20,2026-03-01 04:45,15.81,17.34,1,1,12,...,4.58,5.42,7.08,6,30,0,0,180,0,0

In [128]:
# -------------------------------------------------
# Map rru_power from ltetrafficbands
# based on traffic_load_mbps range
# into df['rru_extra_band']
# -------------------------------------------------

def get_rru_power(traffic):

    match = ltetrafficbands[
        (traffic >= ltetrafficbands['Lower']) &
        (traffic <= ltetrafficbands['Upper'])
    ]

    if not match.empty:
        return match.iloc[0]['rru_power']

    # fallback for traffic above highest range
    return ltetrafficbands['rru_power'].max()

# Apply mapping
df['rru_extra_band'] = df['traffic_load_mbps'].apply(get_rru_power)

# Verify
df[['traffic_load_mbps', 'rru_extra_band']].head(5)

   traffic_load_mbps  rru_extra_band
0              11.90              10
1              12.03              10
2              12.08              10
3              11.96              10
4              12.48              10

In [129]:
df.iloc[10:12]

,Site_ID,Cell_ID,Sector_ID,trigger_ID,datetime,traffic_load_mbps,Total Power,BBU3900,BBU3910,rru_count,...,BBU3900BP,BBU3910BP,lbbp_bp,ltetrfband,ltetrfbandmax,ltetrfbandextrapower,calctotalpower,rru_base_power,rru_extra_band,rru_extra_power
10,101,10111,11,11,2026-03-01 02:30,14.05,17.31,1,1,12,...,4.58,5.42,7.08,3,15,0,0,180,10,0
11,101,10111,11,12,2026-03-01 02:45,14.04,17.31,1,1,12,...,4.58,5.42,7.08,3,15,0,0,180,10,0

In [130]:
# Calculate rru_extra_power

df['rru_extra_power'] = round(
    (
        df['traffic_load_mbps'] *
        df['rru_extra_band']
    ) / df['ltetrfbandmax'],
    2
)

# Verify
df[[
    'traffic_load_mbps',
    'rru_extra_band',
    'ltetrfbandmax',
    'rru_extra_power'
]].head(5)

   traffic_load_mbps  rru_extra_band  ltetrfbandmax  rru_extra_power
0              11.90              10             15             7.93
1              12.03              10             15             8.02
2              12.08              10             15             8.05
3              11.96              10             15             7.97
4              12.48              10             15             8.32

In [131]:
import numpy as np

df["ltetrfbandextrapower"] = np.where(
    (df["ltetrfbandmax"] == 0) | (df["rru_count"] == 0),
    0,
    (
        (df["traffic_load_mbps"] * df["ltetrfband"]) /
        (df["ltetrfbandmax"] * df["rru_count"])
    ).round(2)
)

In [132]:
df[[
    "traffic_load_mbps",
    "ltetrfband",
    "ltetrfbandmax",
    "rru_count",
    "ltetrfbandextrapower"
]].head()

,traffic_load_mbps,ltetrfband,ltetrfbandmax,rru_count,ltetrfbandextrapower
0,11.90,3,15,12,0.20
1,12.03,3,15,12,0.20
2,12.08,3,15,12,0.20
3,11.96,3,15,12,0.20
4,12.48,3,15,12,0.21

In [133]:
df.iloc[1:2]

,Site_ID,Cell_ID,Sector_ID,trigger_ID,datetime,traffic_load_mbps,Total Power,BBU3900,BBU3910,rru_count,...,BBU3900BP,BBU3910BP,lbbp_bp,ltetrfband,ltetrfbandmax,ltetrfbandextrapower,calctotalpower,rru_base_power,rru_extra_band,rru_extra_power
1,101,10111,11,2,2026-03-01 00:15,12.03,17.28,1,1,12,...,4.58,5.42,7.08,3,15,0.2,0,180,10,8.02

In [134]:
df["calctotalpower"] = (
    df["BBU3900BP"] +
    df["BBU3910BP"] +
    df["lbbp_bp"] +
    df["rru_base_power"] +
    df["rru_extra_power"] +
    df["ltetrfbandextrapower"]
).round(2)

In [135]:
df.head()

,Site_ID,Cell_ID,Sector_ID,trigger_ID,datetime,traffic_load_mbps,Total Power,BBU3900,BBU3910,rru_count,...,BBU3900BP,BBU3910BP,lbbp_bp,ltetrfband,ltetrfbandmax,ltetrfbandextrapower,calctotalpower,rru_base_power,rru_extra_band,rru_extra_power
0,101,10111,11,1,2026-03-01 00:00,11.90,17.28,1,1,12,...,4.58,5.42,7.08,3,15,0.20,205.21,180,10,7.93
1,101,10111,11,2,2026-03-01 00:15,12.03,17.28,1,1,12,...,4.58,5.42,7.08,3,15,0.20,205.30,180,10,8.02
2,101,10111,11,3,2026-03-01 00:30,12.08,17.28,1,1,12,...,4.58,5.42,7.08,3,15,0.20,205.33,180,10,8.05
3,101,10111,11,4,2026-03-01 00:45,11.96,17.28,1,1,12,...,4.58,5.42,7.08,3,15,0.20,205.25,180,10,7.97
4,101,10111,11,5,2026-03-01 01:00,12.48,17.29,1,1,12,...,4.58,5.42,7.08,3,15,0.21,205.61,180,10,8.32

In [136]:
#df.to_excel("full data.xlsx", index=False)

Maximum power of a Cell

In [137]:
lte_max_cell = (
    df.groupby(["Site_ID", "Cell_ID"], as_index=False)["calctotalpower"]
    .max()
    .rename(columns={"calctotalpower": "max_cell_power"})
)

lte_max_cell.head()

   Site_ID  Cell_ID  max_cell_power
0      101    10111          230.94
1      101    10112          230.69
2      101    10113          238.01
3      101    10114          245.76
4      101    10121          248.22

In [138]:
lte_max_cell.to_excel("lte_max_cell.xlsx", index=False)

Add Maximum power of all cells per site

In [139]:
lte_max_power_site = (
    lte_max_cell.groupby("Site_ID", as_index=False)["max_cell_power"]
    .sum()
    .rename(columns={"max_cell_power": "max_power"})
)

# Round to 2 decimal points
lte_max_power_site["max_power"] = (
    lte_max_power_site["max_power"].round(2)
)

lte_max_power_site.head()

   Site_ID  max_power
0      101    2777.03
1      102     903.84
2      103    2885.13
3      104     886.97
4      105    2249.47

In [140]:
lte_max_power_site.to_excel("lte_max_power_site.xlsx", index=False)