<a href="https://colab.research.google.com/github/sathkumara-smna/258739K/blob/main/LTE_Eng_Rule.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import pandas as pd

# Raw GitHub file URL
url = "https://raw.githubusercontent.com/sathkumara-smna/258739K/main/LTE_01_03_2026%20-%20Lite.xlsx"
#url = "https://raw.githubusercontent.com/sathkumara-smna/258739K/main/LTE%20Master%20Raw%20Data.xlsx"

# Load Excel file
df = pd.read_excel(url)

# Show first few rows
df.head(2)

,Site_ID,Cell_ID,Sector_ID,trigger_ID,datetime,traffic_load_mbps,Total Power
0,101,10111,11,1,2026-03-01 00:00,11.90,17.28
1,101,10111,11,2,2026-03-01 00:15,12.03,17.28

In [33]:
url1 = "https://raw.githubusercontent.com/sathkumara-smna/258739K/main/4G%20Site%20information.xlsx"

# Load into dataframe
info_4g = pd.read_excel(url1)
info_4g.head(2)

   #  Site_ID        Site Name  lbbp_boards  bbu3900  bbu3910  rru_count
0  1      101     AIRPORT_MAHE            2        1        1         12
1  2      102  AIRPORT_PRASLIN            1        1        0          4

In [35]:
df["rru_count"] = 0
df["bbu3900"] = 0
df["bbu3910"] = 0

df["bbu3900_bp"] = 0
df["bbu3910_bp"] = 0

df["lte_traffic_max"] = 0

df["bbu_power_band"] = 0
df["bbu_extra_power"] = 0

df["lbbp_boards_count"] = 0
df["lbbp_bp"] = 0

df["lbbp_power_band"] = 0
df["lbbp_extra_power"] = 0

df["rru_bp"] = 180

df["rruu_power_band"] = 0
df["rru_extra_power"] = 0

df["calctotalpower"] = 0
df["power_difference"] = 0
df.head(2)

,Site_ID,Cell_ID,Sector_ID,trigger_ID,datetime,traffic_load_mbps,Total Power,rru_count,bbu3900,bbu3910,...,bbu_extra_power,lbbp_boards_count,lbbp_bp,lbbp_power_band,lbbp_extra_power,rru_bp,rruu_power_band,rru_extra_power,calctotalpower,power_difference
0,101,10111,11,1,2026-03-01 00:00,11.90,17.28,0,0,0,...,0,0,0,0,0,180,0,0,0,0
1,101,10111,11,2,2026-03-01 00:15,12.03,17.28,0,0,0,...,0,0,0,0,0,180,0,0,0,0

In [39]:
rru_map = dict(zip(info_4g["Site_ID"], info_4g["rru_count"]))
df["rru_count"] = df["Site_ID"].map(rru_map).fillna(0).astype(int)
df[["Site_ID", "rru_count"]].head(2)

   Site_ID  rru_count
0      101         12
1      101         12

In [ ]:
df.to_excel("rru_count.xlsx", index=False)