<a href="https://colab.research.google.com/github/sathkumara-smna/258739K/blob/main/Site_Power_Prection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

site_db_url = "https://raw.githubusercontent.com/sathkumara-smna/258739K/main/site_power%20from%20Sey.xlsx"
site_db = pd.read_excel(site_db_url)
site_db.head(2)

   Site_ID  trigger_ID        date          datetime  site_power
0      101           1  2026-03-01  2026-03-01 00:00   6517.6299
1      101           2  2026-03-01  2026-03-01 00:15   6533.5512

In [11]:
power_2g3g_url = "https://raw.githubusercontent.com/sathkumara-smna/258739K/main/site_power_2g3g.xlsx"
power_2g3g = pd.read_excel(power_2g3g_url)
power_2g3g.head(2)

,Site_ID,rru_count_2g,rru_2g_bp,power_2g,rru_count_3g,rru_3g_bp,power_3g,total_2g_3g_power
0,101,3,150,450,7,200,1400,1850
1,102,2,150,300,4,200,800,1100

In [12]:
# Add power_2g3g column to site_db using Site_ID matching

site_db['power_2g3g'] = (

    site_db['Site_ID'].map(
        power_2g3g.set_index('Site_ID')['total_2g_3g_power']
    )

)

# Show first rows
site_db.head()

   Site_ID  trigger_ID        date          datetime  site_power  power_2g3g
0      101           1  2026-03-01  2026-03-01 00:00   6517.6299        1850
1      101           2  2026-03-01  2026-03-01 00:15   6533.5512        1850
2      101           3  2026-03-01  2026-03-01 00:30   5861.2925        1850
3      101           4  2026-03-01  2026-03-01 00:45   6290.3504        1850
4      101           5  2026-03-01  2026-03-01 01:00   6282.3500        1850

In [13]:
# Show row for Site_ID = 163

site_db[site_db['Site_ID'] == 163]

,Site_ID,trigger_ID,date,datetime,site_power,power_2g3g
5664,163,1,2026-03-01,2026-03-01 00:00,6202.6875,1200
5665,163,2,2026-03-01,2026-03-01 00:15,6094.6475,1200
5666,163,3,2026-03-01,2026-03-01 00:30,5469.0100,1200
5667,163,4,2026-03-01,2026-03-01 00:45,6020.2794,1200
5668,163,5,2026-03-01,2026-03-01 01:00,5496.6665,1200
...,...,...,...,...,...,...
48955,163,92,2026-03-07,2026-03-07 22:45,6219.0435,1200
48956,163,93,2026-03-07,2026-03-07 23:00,5606.3520,1200
48957,163,94,2026-03-07,2026-03-07 23:15,5723.4615,1200
48958,163,95,2026-03-07,2026-03-07 23:30,5962.0057,1200
48959,163,96,2026-03-07,2026-03-07 23:45,5560.1112,1200

In [14]:
# Show first 4 rows for Site_ID = 163

site_db[site_db['Site_ID'] == 163].head(4)

,Site_ID,trigger_ID,date,datetime,site_power,power_2g3g
5664,163,1,2026-03-01,2026-03-01 00:00,6202.6875,1200
5665,163,2,2026-03-01,2026-03-01 00:15,6094.6475,1200
5666,163,3,2026-03-01,2026-03-01 00:30,5469.0100,1200
5667,163,4,2026-03-01,2026-03-01 00:45,6020.2794,1200